### ISSUE TITLE
Verify package bundle can be imported into a React app

### ISSUE THREAD

**Issue by adamjarling** [IIIF-Commons/thumbnail-panel#21]
@mathewjordan has had some issues trying to import the `build` version of the component into a separate React app.   Let's investigate why.

## Done looks like
- NPM version created via Github Action.
- We get the `NPM_TOKEN` value (@glenrobson) and plug it into Github to allow the Action
- The `v0.0.1` release on NPM can be imported into an application

**Comment by glenrobson** [comment]
Stephen added the NPM_TOKEN and it now deploys to NPM on repo tag:

https://www.npmjs.com/package/@iiif/thumbnail-panel

**Comment by glenrobson** [comment]
Done
